version: '3'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis-server  # Set the hostname for Redis
    depends_on:
      - redis-server

  redis-server:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
